Updated with work configuration

diff --git a/Scripts/Utilities/print-color b/Scripts/Utilities/print-color
--- a/Scripts/Utilities/print-color
+++ b/Scripts/Utilities/print-color
@@ -8,7 +8,8 @@ black='\033[0;30m'
 white='\033[0;37m'
 red='\033[0;31m'
 green='\033[0;32m'
-yellow='\033[0;33m'
+yellow='\033[1;93m'
+yellow2='\033[0;33m'
 blue='\033[0;34m'
 magenta='\033[0;35m'
 cyan='\033[0;36m'
@@ -23,7 +24,16 @@ function printMessage() {
       echo -e "${BIRed} A message parameter is required ${Color_Off}"
       exit 1
   fi
-  echo -e "${BIBlue} $1 ${Color_Off}"
+  echo -e "${white} $1 ${Color_Off}"
+}
+
+function print_question() {
+  if [ $# -eq 0 ]
+    then
+      echo -e "${BIRed} A message parameter is required ${Color_Off}"
+      exit 1
+  fi
+  echo -e "${question_color} $1 ${_reset}"
 }
 
 function printErrorMessage() {
