Improved CLI

diff --git a/Scripts/Utilities/print-color b/Scripts/Utilities/print-color
--- a/Scripts/Utilities/print-color
+++ b/Scripts/Utilities/print-color
@@ -1,9 +1,46 @@
 #!/usr/bin/env bash
 
-BIBlue='\033[1;94m' # Blue
+# Colors
 Color_Off='\033[0m' # No Color
+BIBlue='\033[1;94m' # Blue
+BIRed="\033[1;91m"
+black='\033[0;30m'
+white='\033[0;37m'
+red='\033[0;31m'
+green='\033[0;32m'
+yellow='\033[0;33m'
+blue='\033[0;34m'
+magenta='\033[0;35m'
+cyan='\033[0;36m'
+
+# Resets the style
+_reset=`tput sgr0`
 
 
 function printMessage() {
+  if [ $# -eq 0 ]
+    then
+      echo -e "${BIRed} A message parameter is required ${Color_Off}"
+      exit 1
+  fi
   echo -e "${BIBlue} $1 ${Color_Off}"
+}
+
+function printErrorMessage() {
+  if [ $# -eq 0 ]
+    then
+      echo -e "${BIRed} A message parameter is required ${Color_Off}"
+      exit 1
+  fi
+  echo -e "${BIRed} $1 ${Color_Off}"
+}
+
+# Color-echo. [Inspired by @cdzombak]
+# arg $1 = message
+# arg $2 = Color
+cecho() {
+  echo -ne "${2}"
+  echo -n "${1}"
+  echo -e "${_reset}"
+  return
 }
